name: dotnetinterop
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  equatable: ^2.0.5
  ffi: ^2.0.1 
  win32: ^3.0.0


dev_dependencies:
  lints: ^1.0.0
  ffigen: ^6.0.1
  recharge: ^0.1.0

  
